# Generated by Django 4.1.5 on 2023-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_alter_genre_name_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
